[package]
name = "dice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf8_slice = "1.0.0"
tinytemplate = "1.2.1"
serde = { version = "1.0", features = ["derive"] }